version: "3"
services:
  redis:
    image: redis
    ports: 
      - "6380:6379"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users
      NODE_ENV: docker
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  migration:
    build: 
      context: .
      dockerfile: Dockerfile.migration
    depends_on:
      - db
      - redis

    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: users
      DB_PORT: 5432
      NODE_ENV: docker
    
  server:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: users
      DB_PORT: 5432
      NODE_ENV: docker
      REDIS_HOST: redis
      REDIS_PORT: 6379