version: "3"
services:
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: null
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: null
      DB_NAME: users
      DB_PORT: 5432