version: "3"
services:
  redis:
    image: redis

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users

  migration:
    build: .
    depends_on:
      - db
      - redis
    command: npx sequelize-cli db:migrate
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: users
      DB_PORT: 5432
    
  server:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: users
      DB_PORT: 5432